---

services:
  polpa_db:
    image: postgres:15
    container_name: polpa_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - polpa-network

  polpa_prisma:
    build:
      context: ./backend
      target: prisma
    image: ghcr.io/rmcampos/polpa-gestao/backend-prisma:latest
    container_name: polpa_prisma
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@polpa_db:5432/${DB_NAME}
    command: ["npx", "prisma", "migrate", "deploy"]
    depends_on:
      polpa_db:
        condition: service_healthy
    restart: "no"
    networks:
      - polpa-network

  polpa_backend:
    build: ./backend
    image: ghcr.io/rmcampos/polpa-gestao/backend:latest
    container_name: polpa_backend
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@polpa_db:5432/${DB_NAME}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      polpa_db:
        condition: service_healthy
      polpa_prisma:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - polpa-network

  polpa_frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_SERVER: http://localhost:3000
        VITE_CPF_CNPJ_API_TOKEN: ${CPF_CNPJ_API_TOKEN}
        VITE_GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
        VITE_BUILD_NUMBER: snapshot
    image: ghcr.io/rmcampos/polpa-gestao/frontend:latest
    container_name: polpa_frontend
    ports:
      - "5173:80"
    depends_on:
      - polpa_backend
    networks:
      - polpa-network

volumes:
  pgdata:
networks:
  polpa-network:
    external: true
