---

services:
  postgres:
    image: postgres:15
    container_name: polpa_gestao_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: polpa_gestao
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d polpa_gestao"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - polpa-network

  prisma-push:
    build:
      context: ./backend
      target: prisma
    image: ghcr.io/rmcampos/polpa-gestao/backend-prisma:latest
    container_name: polpa_gestao_prisma_push
    environment:
      DATABASE_URL: postgres://admin:adminpassword@postgres:5432/polpa_gestao
    command: ["npx", "prisma", "migrate", "deploy"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - polpa-network

  backend:
    build: ./backend
    image: ghcr.io/rmcampos/polpa-gestao/backend:latest
    container_name: polpa_gestao_backend
    environment:
      DATABASE_URL: postgres://admin:adminpassword@postgres:5432/polpa_gestao
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      prisma-push:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - polpa-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_SERVER: http://localhost:3000
        VITE_CPF_CNPJ_API_TOKEN: ${VITE_CPF_CNPJ_API_TOKEN}
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
        VITE_BUILD_NUMBER: snapshot
    image: ghcr.io/rmcampos/polpa-gestao/frontend:latest
    container_name: polpa_gestao_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - polpa-network

volumes:
  pgdata:
networks:
  polpa-network:
    external: true
